import "./globals.scss";
import Head from "next/head";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-[#010101] scrollbar-hidden">
        <main>{children}</main>
      </body>
    </html>
  );
}
